import { i18next } from "@/i18n";
import type { FilterOperator, ViewType } from "@/lib/types";

export function databaseViewLabels() {
  const tr = (key: string, options?: Record<string, unknown>): string =>
    i18next.t(`databaseView:${key}`, options ?? {});
  const common = (key: string): string => i18next.t(`common:${key}`);
  return {
    addComment: tr("addComment"),
    addCommentTo: (title: string) => tr("addCommentTo", { title }),
    addDateProperty: tr("addDateProperty"),
    addEndDateProperty: tr("addEndDateProperty"),
    addNewView: tr("addNewView"),
    addToFavorites: (title: string) => tr("addToFavorites", { title }),
    addedToFavorites: tr("addedToFavorites"),
    aiAutofill: tr("aiAutofill"),
    automations: tr("automations"),
    backToProperties: tr("backToProperties"),
    backToPropertyList: tr("backToPropertyList"),
    backToViewSettings: tr("backToViewSettings"),
    calendarBy: tr("calendarBy"),
    calendarView: tr("calendarView"),
    cannotAddCalendarView: tr("cannotAddCalendarView"),
    cardPreview: tr("cardPreview"),
    cardSize: tr("cardSize"),
    center: tr("center"),
    changeIcon: tr("changeIcon"),
    changeTemplateIcon: tr("changeTemplateIcon"),
    close: tr("close"),
    closeProperties: tr("closeProperties"),
    closePropertyVisibility: tr("closePropertyVisibility"),
    closeTemplateEditor: (title: string) => tr("closeTemplateEditor", { title }),
    closeViewSettings: tr("closeViewSettings"),
    collapseTemplateEditor: tr("collapseTemplateEditor"),
    comments: tr("comments"),
    conditionalColor: tr("conditionalColor"),
    copiedViewLink: tr("copiedViewLink"),
    copyLink: (title: string) => tr("copyLink", { title }),
    copyLinkFailed: tr("copyLinkFailed"),
    copyShareLink: (title: string) => tr("copyShareLink", { title }),
    copyViewLink: tr("copyViewLink"),
    copyViewLinkFailed: tr("copyViewLinkFailed"),
    countSuffix: (count: number) => tr("countSuffix", { count }),
    createEmptyPage: tr("createEmptyPage"),
    choosePage: tr("choosePage"),
    createPropertyFailed: tr("createPropertyFailed"),
    createTemplate: tr("createTemplate"),
    createTemplateAria: tr("createTemplateAria"),
    createWithoutTemplate: tr("createWithoutTemplate"),
    createdProperty: (name: string) => tr("createdProperty", { name }),
    currentPage: tr("currentPage"),
    dataSourceSettings: tr("dataSourceSettings"),
    database: tr("database"),
    databaseFallbackTitle: tr("databaseFallbackTitle"),
    day: tr("day"),
    defaultLabel: tr("defaultLabel"),
    defaultSuffix: tr("defaultSuffix"),
    defaultTemplateForNewPages: tr("defaultTemplateForNewPages"),
    deleteProperty: tr("deleteProperty"),
    deletePropertyFailed: tr("deletePropertyFailed"),
    confirmDeleteProperty: (name: string) => tr("confirmDeleteProperty", { name }),
    deleteTemplateAria: (name: string) => tr("deleteTemplateAria", { name }),
    deleteView: tr("deleteView"),
    deletedProperties: tr("deletedProperties"),
    deletedPropertiesNotLinked: tr("deletedPropertiesNotLinked"),
    deletedProperty: tr("deletedProperty"),
    duplicate: tr("duplicate"),
    duplicateGive: tr("duplicateGive"),
    duplicateTemplateAria: (name: string) => tr("duplicateTemplateAria", { name }),
    duplicateView: tr("duplicateView"),
    edit: tr("edit"),
    editProperties: tr("editProperties"),
    editingTemplateIn: tr("editingTemplateIn"),
    expandTemplateEditor: tr("expandTemplateEditor"),
    filter: tr("filter"),
    fitImage: tr("fitImage"),
    full: tr("full"),
    group: tr("group"),
    hiddenCountSuffix: (count: number) => tr("hiddenCountSuffix", { count }),
    hideAll: tr("hideAll"),
    hiddenInTable: tr("hiddenInTable"),
    initialLoad: tr("initialLoad"),
    large: tr("large"),
    layout: tr("layout"),
    linkCopied: (title: string) => tr("linkCopied", { title }),
    linkCopiedToast: tr("linkCopiedToast"),
    loadLimit: tr("loadLimit"),
    loadMore: tr("loadMore"),
    loadingDatabase: tr("loadingDatabase"),
    loadingMore: tr("loadingMore"),
    locked: tr("locked"),
    me: tr("me"),
    medium: tr("medium"),
    month: tr("month"),
    moreSettings: tr("moreSettings"),
    moreViews: (count: number) => tr("moreViews", { count }),
    newDatabasePage: tr("newDatabasePage"),
    newFromTemplate: (name: string) => tr("newFromTemplate", { name }),
    newPage: tr("newPage"),
    newPageFromTemplate: (name: string) => tr("newPageFromTemplate", { name }),
    newPageMenuItem: tr("newPageMenuItem"),
    newProperty: tr("newProperty"),
    newPropertyIn: (title: string) => tr("newPropertyIn", { title }),
    newTemplate: tr("newTemplate"),
    noDateProperties: tr("noDateProperties"),
    noSearchResults: tr("noSearchResults"),
    noTemplates: tr("noTemplates"),
    noTemplatesFound: tr("noTemplatesFound"),
    noViewToCopy: tr("noViewToCopy"),
    noViewToDuplicate: tr("noViewToDuplicate"),
    none: tr("none"),
    openActions: (title: string) => tr("openActions", { title }),
    openAsFullPage: tr("openAsFullPage"),
    openAsPage: (title: string) => tr("openAsPage", { title }),
    openComments: (title: string, count: number) => tr("openComments", { title, count }),
    openPagesIn: tr("openPagesIn"),
    openTemplateActions: tr("openTemplateActions"),
    pageCover: tr("pageCover"),
    peekOptions: (title: string) => tr("peekOptions", { title }),
    closePeek: (title: string) => tr("closePeek", { title }),
    properties: tr("properties"),
    propertyHelp: tr("propertyHelp"),
    propertyHelpNotLinked: tr("propertyHelpNotLinked"),
    propertyVisibility: tr("propertyVisibility"),
    removeFromFavorites: (title: string) => tr("removeFromFavorites", { title }),
    removedFromFavorites: tr("removedFromFavorites"),
    renamedView: tr("renamedView"),
    restorePropertyFailed: tr("restorePropertyFailed"),
    restoredProperty: tr("restoredProperty"),
    rowHeight: tr("rowHeight"),
    searchProperties: tr("searchProperties"),
    searchTemplates: tr("searchTemplates"),
    setDefault: tr("setDefault"),
    share: tr("share"),
    short: tr("short"),
    shownInTable: tr("shownInTable"),
    showAll: tr("showAll"),
    showTable: tr("showTable"),
    side: tr("side"),
    small: tr("small"),
    sort: tr("sort"),
    tall: tr("tall"),
    templateBodyPlaceholder: tr("templateBodyPlaceholder"),
    templatePageTitlePlaceholder: tr("templatePageTitlePlaceholder"),
    templateSearchLabel: tr("templateSearchLabel"),
    templateViewOptions: (title: string) => tr("templateViewOptions", { title }),
    timeUnit: tr("timeUnit"),
    timelineBy: tr("timelineBy"),
    timelineEndDate: tr("timelineEndDate"),
    timelineZoomAria: tr("timelineZoomAria"),
    toolbarNew: tr("toolbarNew"),
    type: tr("type"),
    unlock: (title: string) => tr("unlock", { title }),
    updateFavoritesFailed: tr("updateFavoritesFailed"),
    viewName: tr("viewName"),
    viewsFor: (title: string) => tr("viewsFor", { title }),
    viewActionsFor: (name: string) => tr("viewActionsFor", { name }),
    rowPreviewFor: (title: string) => tr("rowPreviewFor", { title }),
    viewSettings: tr("viewSettings"),
    viewSettingsLabel: tr("viewSettingsLabel"),
    viewTypes: {
      table: tr("viewTypes.table"),
      board: tr("viewTypes.board"),
      gallery: tr("viewTypes.gallery"),
      list: tr("viewTypes.list"),
      timeline: tr("viewTypes.timeline"),
      calendar: tr("viewTypes.calendar"),
      chart: tr("viewTypes.chart"),
    } as Record<ViewType, string>,
    viewTypeDescriptions: {
      table: tr("viewTypeDescriptions.table"),
      board: tr("viewTypeDescriptions.board"),
      gallery: tr("viewTypeDescriptions.gallery"),
      list: tr("viewTypeDescriptions.list"),
      timeline: tr("viewTypeDescriptions.timeline"),
      calendar: tr("viewTypeDescriptions.calendar"),
      chart: tr("viewTypeDescriptions.chart"),
    } as Record<ViewType, string>,
    week: tr("week"),
    wrapProperties: tr("wrapProperties"),
    addIcon: tr("addIcon"),
    addTemplateIcon: tr("addTemplateIcon"),
    newFromTemplatesLabel: tr("newFromTemplatesLabel"),
    toast: {
      couldntCreateDefaultTableView: tr("toast.couldntCreateDefaultTableView"),
      couldntCreateView: tr("toast.couldntCreateView"),
      couldntDuplicateView: tr("toast.couldntDuplicateView"),
      duplicatedView: tr("toast.duplicatedView"),
      createdView: tr("toast.createdView"),
      removedViewFromInline: tr("toast.removedViewFromInline"),
      couldntDeleteView: tr("toast.couldntDeleteView"),
      deletedView: tr("toast.deletedView"),
      couldntRestoreView: tr("toast.couldntRestoreView"),
      restoredView: tr("toast.restoredView"),
      pageUnlocked: tr("toast.pageUnlocked"),
      clearedFilters: tr("toast.clearedFilters"),
      restoredFilters: tr("toast.restoredFilters"),
      clearedSort: tr("toast.clearedSort"),
      clearedSorts: tr("toast.clearedSorts"),
      restoredSort: tr("toast.restoredSort"),
      restoredSorts: tr("toast.restoredSorts"),
      createdTemplate: tr("toast.createdTemplate"),
      couldntCreateTemplate: tr("toast.couldntCreateTemplate"),
      couldntDuplicateTemplate: tr("toast.couldntDuplicateTemplate"),
      couldntUpdateTemplate: tr("toast.couldntUpdateTemplate"),
      couldntCreateRowFromTemplate: tr("toast.couldntCreateRowFromTemplate"),
      storedFileTemplateApplyBlocked: tr("toast.storedFileTemplateApplyBlocked"),
      storedFileTemplateDuplicateBlocked: tr("toast.storedFileTemplateDuplicateBlocked"),
      duplicatedTemplate: tr("toast.duplicatedTemplate"),
      setDefaultTemplate: tr("toast.setDefaultTemplate"),
      defaultTemplateRemoved: tr("toast.defaultTemplateRemoved"),
      couldntDeleteTemplate: tr("toast.couldntDeleteTemplate"),
      deletedTemplate: tr("toast.deletedTemplate"),
      restoredTemplate: tr("toast.restoredTemplate"),
      couldntRestoreTemplate: tr("toast.couldntRestoreTemplate"),
    },
    addView: tr("addView"),
    addAView: tr("addAView"),
    viewType: tr("viewType"),
    defaultView: tr("defaultView"),
    closeAddViewMenu: tr("closeAddViewMenu"),
    closeViewActions: tr("closeViewActions"),
    closeHiddenViews: tr("closeHiddenViews"),
    hiddenViews: tr("hiddenViews"),
    closeRowPreview: tr("closeRowPreview"),
    resizeSidePreview: tr("resizeSidePreview"),
    databaseToolbar: tr("databaseToolbar"),
    closeLayoutOptions: tr("closeLayoutOptions"),
    layoutOptions: tr("layoutOptions"),
    databaseViewType: tr("databaseViewType"),
    openDatabasePagesIn: tr("openDatabasePagesIn"),
    tableRowHeight: tr("tableRowHeight"),
    closeGroupOptions: tr("closeGroupOptions"),
    groupBy: tr("groupBy"),
    closePropertiesMenu: tr("closePropertiesMenu"),
    closeSourcePropertiesMenu: tr("closeSourcePropertiesMenu"),
    name: tr("name"),
    description: tr("description"),
    addDescription: tr("addDescription"),
    closeFiltersMenu: tr("closeFiltersMenu"),
    filters: tr("filters"),
    closeSortsMenu: tr("closeSortsMenu"),
    sorts: tr("sorts"),
    searchDatabaseRows: tr("searchDatabaseRows"),
    closeSearch: tr("closeSearch"),
    openDatabaseAsPage: tr("openDatabaseAsPage"),
    openAsPageShort: tr("openAsPageShort"),
    databaseSettings: tr("databaseSettings"),
    settings: tr("settings"),
    chooseDatabaseTemplate: tr("chooseDatabaseTemplate"),
    closeNewPageMenu: tr("closeNewPageMenu"),
    closeTemplateEditorPlain: tr("closeTemplateEditorPlain"),
    editDatabaseTemplate: tr("editDatabaseTemplate"),
    closeTemplateActions: tr("closeTemplateActions"),
    templatePageTitle: tr("templatePageTitle"),
    removeFilterGroup: tr("removeFilterGroup"),
    removeFilter: tr("removeFilter"),
    dragProperty: (name: string) => tr("dragProperty", { name }),
    hideProperty: (name: string) => tr("hideProperty", { name }),
    showProperty: (name: string) => tr("showProperty", { name }),
    moveSortUp: tr("moveSortUp"),
    moveSortDown: tr("moveSortDown"),
    removeSort: tr("removeSort"),
    value: tr("value"),
    untitled: tr("untitled"),
    unsupported: tr("unsupported"),
    unsupportedViewTitle: (type: string) => tr("unsupportedViewTitle", { type }),
    unsupportedViewBody: tr("unsupportedViewBody"),
    chooseViewAppearance: tr("chooseViewAppearance"),
    cancel: common("actions.cancel"),
    create: common("actions.create"),
    clearAll: common("actions.clearAll"),
    search: common("actions.search"),
    undo: tr("undo"),
    copyName: (name: string) => tr("copyName", { name }),
    and: tr("and"),
    or: tr("or"),
    filterGroup: tr("filterGroup"),
    addFilter: tr("addFilter"),
    addFilterGroup: tr("addFilterGroup"),
    filterProperty: tr("filterProperty"),
    filterCondition: tr("filterCondition"),
    filterValueFor: (name: string) => tr("filterValueFor", { name }),
    sortProperty: tr("sortProperty"),
    sortDirection: tr("sortDirection"),
    ascending: tr("ascending"),
    descending: tr("descending"),
    checked: tr("checked"),
    unchecked: tr("unchecked"),
    chooseOption: tr("chooseOption"),
    choosePerson: tr("choosePerson"),
    propertyType: tr("propertyType"),
    groupEmpty: tr("groupEmpty"),
    addStatusProperty: tr("addStatusProperty"),
    addSelectProperty: tr("addSelectProperty"),
    filtersEmpty: tr("filtersEmpty"),
    sortsEmpty: tr("sortsEmpty"),
    addSort: tr("addSort"),
    defaultPropertyNames: {
      status: tr("defaultPropertyNames.status"),
      select: tr("defaultPropertyNames.select"),
      date: tr("defaultPropertyNames.date"),
      endDate: tr("defaultPropertyNames.endDate"),
    },
    defaultStatusOptions: {
      notStarted: tr("defaultStatusOptions.notStarted"),
      inProgress: tr("defaultStatusOptions.inProgress"),
      done: tr("defaultStatusOptions.done"),
      option1: tr("defaultStatusOptions.option1"),
      option2: tr("defaultStatusOptions.option2"),
    },
  };
}

export function filterOperatorLabels(): Record<FilterOperator, string> {
  const tr = (key: string) => i18next.t(`databaseView:operators.${key}`);
  return {
    equals: tr("equals"),
    does_not_equal: tr("does_not_equal"),
    contains: tr("contains"),
    does_not_contain: tr("does_not_contain"),
    is_empty: tr("is_empty"),
    is_not_empty: tr("is_not_empty"),
    greater_than: tr("greater_than"),
    less_than: tr("less_than"),
    on_or_before: tr("on_or_before"),
    on_or_after: tr("on_or_after"),
  };
}

export const NO_VALUE_FILTERS = new Set<FilterOperator>(["is_empty", "is_not_empty"]);
export const NUMERIC_ROLLUP_FUNCTIONS = new Set([
  "count_all",
  "count_values",
  "count_unique",
  "count_empty",
  "percent_empty",
  "percent_not_empty",
  "checked",
  "unchecked",
  "percent_checked",
  "percent_unchecked",
  "sum",
  "average",
  "median",
  "min",
  "max",
  "range",
]);
export const DATE_ROLLUP_FUNCTIONS = new Set(["earliest_date", "latest_date", "date_range"]);
