#!/usr/bin/env sh
# Hanji self-hosted Docker launcher.
#
# One command brings up the whole app over HTTPS on localhost. It builds the
# EdgeBase image if needed, issues a locally-trusted certificate (via mkcert
# when available, otherwise a self-signed one), and runs the container with TLS
# so release-mode cookie sign-in works. The image persists its own runtime
# secrets under /data; a fresh instance asks for its logged setup code and first
# administrator in the browser. Re-running reuses the same secrets, cert, and
# data.
#
# Usage:
#   scripts/selfhost-docker.sh up [--port N] [--email you@example.com]
#                                 [--password PW] [--build]
#                                 [--http --origin https://hanji.example.com]
#   scripts/selfhost-docker.sh down
#   scripts/selfhost-docker.sh logs
#   scripts/selfhost-docker.sh status
#
# Flags:
#   --port N       Host/container port (default 8443).
#   --email EMAIL  Advanced/legacy env-provisioned master account email.
#   --password PW  Advanced/legacy master password (generated if omitted).
#   --data SRC     Where /data lives: a Docker volume name (default hanji-data)
#                  or an absolute host path to bind-mount for the data.
#   --build        Force a fresh image build even if one exists.
#   --http         Serve plain HTTP on 127.0.0.1 only, behind a TLS-terminating
#                  proxy. Requires --origin with the public HTTPS URL.
#   --origin URL   Public HTTPS origin for --http proxy mode.
#
# Environment:
#   HANJI_DOCKER_MIN_FREE_KB  Persistence free-space floor (default 524288).
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(dirname -- "$SCRIPT_DIR")
STATE_DIR="$ROOT/.edgebase/docker"        # gitignored: secrets + certs live here
ENV_FILE="$STATE_DIR/hanji.env"
CERT_DIR="$STATE_DIR/certs"
IMAGE="hanji:latest"
CONTAINER="hanji"
VOLUME="hanji-data"
CERT_VOLUME="hanji-certs"

PORT=8443
SCHEME=https
FORCE_BUILD=0
MASTER_EMAIL=""
MASTER_PASSWORD=""
PUBLIC_ORIGIN=""
ENV_ENABLED=0
DATA_TARGET="$VOLUME"
DATA_KIND=volume
MIN_PERSIST_FREE_KB=${HANJI_DOCKER_MIN_FREE_KB:-524288}

log()  { printf '\033[36m▸\033[0m %s\n' "$*"; }
ok()   { printf '\033[32m✔\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

rand_hex() { openssl rand -hex "${1:-32}"; }

need_docker() {
  command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker first."
  docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and retry."
}

ensure_image() {
  if [ "$FORCE_BUILD" -eq 1 ] || ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    log "Building web bundle + EdgeBase Docker image ($IMAGE)…"
    npm --prefix "$ROOT/web" run build
    node "$ROOT/scripts/build-hanji-docker-image.mjs" --tag "$IMAGE"
    ok "Image built: $IMAGE"
  else
    ok "Reusing existing image: $IMAGE (pass --build to rebuild)"
  fi
}

prepare_env() {
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR"
  if [ -f "$ENV_FILE" ]; then
    ENV_ENABLED=1
    ok "Reusing legacy/advanced environment: $ENV_FILE"
    if [ -n "$MASTER_EMAIL$MASTER_PASSWORD" ]; then
      warn "--email/--password ignored; $ENV_FILE already exists."
    fi
  elif [ -n "$MASTER_EMAIL$MASTER_PASSWORD" ]; then
    ENV_ENABLED=1
    log "Creating advanced env-provisioned master account → $ENV_FILE"
    email=${MASTER_EMAIL:-master@example.com}
    # Keep generated bootstrap credentials above a 128-bit random floor. The
    # password is printed only once and persisted in the mode-0600 env file.
    password=${MASTER_PASSWORD:-"Hanji-$(rand_hex 16)"}
    umask 077
    cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/selfhost-docker.sh. Gitignored. Keep secret.
JWT_USER_SECRET=$(rand_hex 32)
JWT_ADMIN_SECRET=$(rand_hex 32)
SERVICE_KEY=$(rand_hex 32)
HANJI_NOTION_IMPORT_SECRET=$(rand_hex 32)
HANJI_MCP_OAUTH_SECRET=$(rand_hex 32)
HANJI_MASTER_EMAIL=$email
HANJI_MASTER_PASSWORD=$password
HANJI_AUTH_EMAIL_FROM=no-reply@example.com
EOF
    ok "Advanced environment written (master: $email)"
  else
    ok "Using image-managed secrets and browser first-run setup."
  fi
  if [ "$ENV_ENABLED" -eq 1 ]; then
    # Repair permissions on older state created before the launcher enforced a
    # private umask. Docker's --env-file must never be readable by other users.
    chmod 600 "$ENV_FILE"
  fi
}

# Sets global CERT_ARGS (docker args for the cert mount) and TLS_NOTE.
CERT_ARGS=""
TLS_NOTE=""
ensure_cert() {
  [ "$SCHEME" = https ] || { CERT_ARGS=""; return; }
  mkdir -p "$CERT_DIR"
  chmod 700 "$CERT_DIR"
  if command -v mkcert >/dev/null 2>&1; then
    if [ ! -f "$CERT_DIR/cert.pem" ] || [ ! -f "$CERT_DIR/key.pem" ]; then
      log "Issuing locally-trusted certificate via mkcert…"
      mkcert -cert-file "$CERT_DIR/cert.pem" -key-file "$CERT_DIR/key.pem" \
        localhost 127.0.0.1 ::1 >/dev/null 2>&1
    fi
    chmod 600 "$CERT_DIR/key.pem"
    chmod 644 "$CERT_DIR/cert.pem"
    # A native-Linux host does not map the host user's UID to the image's
    # non-root edgebase UID. Copy into a Docker-owned volume so the private key
    # stays 0600 both on the host and in the container instead of weakening it
    # to a world-readable bind mount.
    docker volume create "$CERT_VOLUME" >/dev/null
    docker run --rm --user 0:0 --entrypoint sh \
      -v "$CERT_DIR:/source:ro" -v "$CERT_VOLUME:/target" "$IMAGE" -c \
      'set -eu; cp /source/cert.pem /target/cert.pem; cp /source/key.pem /target/key.pem; chown 10001:10001 /target/cert.pem /target/key.pem; chmod 644 /target/cert.pem; chmod 600 /target/key.pem'
    CERT_ARGS="-v $CERT_VOLUME:/certs:ro -e HTTPS_CERT_PATH=/certs/cert.pem -e HTTPS_KEY_PATH=/certs/key.pem"
    TLS_NOTE="mkcert certificate mounted. If the browser still warns, run: mkcert -install  (then fully reload)."
  else
    warn "mkcert not found → Wrangler will self-sign. Browser shows a one-time warning."
    warn "For a no-warning padlock: brew install mkcert && mkcert -install, then re-run this script."
    CERT_ARGS=""   # no cert paths → wrangler auto-generates a self-signed cert
    TLS_NOTE="Self-signed certificate. Browser warns once: Advanced → proceed."
  fi
}

wait_health() {
  log "Waiting for runtime and product database readiness …"
  i=0
  while [ "$i" -lt 60 ]; do
    runtime_code=$(curl -sk --connect-timeout 1 --max-time 2 -o /dev/null -w '%{http_code}' "$SCHEME://localhost:$PORT/api/health" 2>/dev/null || echo 000)
    product_code=$(curl -sk --connect-timeout 1 --max-time 2 -o /dev/null -w '%{http_code}' "$SCHEME://localhost:$PORT/api/functions/health" 2>/dev/null || echo 000)
    [ "$runtime_code" = 200 ] && [ "$product_code" = 200 ] && { ok "Runtime and product database are healthy."; return 0; }
    i=$((i + 1)); sleep 1
  done
  warn "Health check timed out (runtime=$runtime_code, product=$product_code). Recent logs:"
  docker logs --tail 20 "$CONTAINER" 2>&1 || true
  return 1
}

check_persist_capacity() {
  case "$MIN_PERSIST_FREE_KB" in
    ''|*[!0-9]*) die "HANJI_DOCKER_MIN_FREE_KB must be a non-negative integer." ;;
  esac
  available_kb=$(docker exec "$CONTAINER" df -Pk /data 2>/dev/null | awk 'NR == 2 { print $4 }')
  case "$available_kb" in
    ''|*[!0-9]*)
      docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
      die "Could not verify free space for the Docker persistence volume."
      ;;
  esac
  if [ "$available_kb" -lt "$MIN_PERSIST_FREE_KB" ]; then
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    die "Docker persistence storage is too full (${available_kb} KiB free; require at least ${MIN_PERSIST_FREE_KB} KiB). Free Docker disk space and retry. The data volume was kept."
  fi
  ok "Persistence storage has ${available_kb} KiB free."
}

validate_up_options() {
  case "$PORT" in
    ''|*[!0-9]*) die "--port must be an integer from 1 to 65535." ;;
  esac
  if [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then
    die "--port must be an integer from 1 to 65535."
  fi
  case "$MIN_PERSIST_FREE_KB" in
    ''|*[!0-9]*) die "HANJI_DOCKER_MIN_FREE_KB must be a non-negative integer." ;;
  esac
  case "$MASTER_EMAIL" in
    *[![:print:]]*) die "--email must not contain control characters." ;;
  esac
  if [ -n "$MASTER_EMAIL" ] && ! printf '%s' "$MASTER_EMAIL" | grep -Eq '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'; then
    die "--email must be a valid email address."
  fi
  case "$MASTER_PASSWORD" in
    *[![:print:]]*) die "--password must not contain control characters." ;;
  esac
  if [ -n "$MASTER_PASSWORD" ]; then
    if [ "${#MASTER_PASSWORD}" -lt 16 ] \
      || ! printf '%s' "$MASTER_PASSWORD" | grep -q '[[:lower:]]' \
      || ! printf '%s' "$MASTER_PASSWORD" | grep -q '[[:upper:]]' \
      || ! printf '%s' "$MASTER_PASSWORD" | grep -q '[[:digit:]]' \
      || ! printf '%s' "$MASTER_PASSWORD" | grep -q '[^[:alnum:][:space:]]'; then
      die "--password must be at least 16 characters and include upper, lower, digit, and special characters."
    fi
  fi

  if [ "$SCHEME" = http ]; then
    [ -n "$PUBLIC_ORIGIN" ] || die "--http requires --origin https://your-hanji-host."
    case "$PUBLIC_ORIGIN" in
      https://*) ;;
      *) die "--origin must be an https:// URL." ;;
    esac
    if ! PASSKEY_RP_ID=$(node -e 'const u=new URL(process.argv[1]);if(u.username||u.password||u.pathname!=="/"||u.search||u.hash)process.exit(1);process.stdout.write(u.hostname)' "$PUBLIC_ORIGIN" 2>/dev/null); then
      die "--origin must contain only a valid public HTTPS origin (no path, query, or credentials)."
    fi
  elif [ -n "$PUBLIC_ORIGIN" ]; then
    die "--origin is only used together with --http."
  fi

  # Resolve where /data lives: an absolute host path (bind mount) or a Docker
  # volume name (no slashes). Reject ambiguous relative paths.
  case "$DATA_TARGET" in
    '')                die "--data must not be empty." ;;
    /*)                DATA_KIND=path; mkdir -p "$DATA_TARGET" || die "Could not create data directory: $DATA_TARGET" ;;
    */*)               die "--data must be an absolute path (e.g. /srv/hanji-data) or a plain Docker volume name (no slashes)." ;;
    *[![:alnum:]_.-]*) die "--data volume name may contain only letters, digits, and _.- characters." ;;
    *)                 DATA_KIND=volume ;;
  esac
}

cmd_up() {
  need_docker
  ensure_image
  prepare_env
  ensure_cert

  [ "$SCHEME" = https ] && proto=https || proto=http
  internal_origin="$proto://localhost:$PORT"
  if [ "$SCHEME" = http ]; then
    origin="$PUBLIC_ORIGIN"
    publish="127.0.0.1:$PORT:$PORT"
    proxy_args="-e HANJI_TRUST_SELF_HOSTED_PROXY=true"
    passkey_rp_id="$PASSKEY_RP_ID"
  else
    origin="$internal_origin"
    publish="$PORT:$PORT"
    proxy_args=""
    passkey_rp_id=localhost
  fi

  log "Starting container '$CONTAINER' on $origin"
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  # shellcheck disable=SC2086  # CERT_ARGS is an intentional word list
  if [ "$ENV_ENABLED" -eq 1 ]; then
    docker run -d --name "$CONTAINER" \
      -p "$publish" -e PORT="$PORT" \
      -v "$DATA_TARGET:/data" \
      --env-file "$ENV_FILE" \
      -e LOCAL_PROTOCOL="$SCHEME" \
      -e HANJI_APP_ORIGIN="$origin" \
      -e HANJI_PASSKEY_RP_ID="$passkey_rp_id" \
      -e HANJI_PASSKEY_ORIGINS="$origin" \
      $proxy_args \
      $CERT_ARGS \
      --restart unless-stopped "$IMAGE" >/dev/null
  else
    docker run -d --name "$CONTAINER" \
      -p "$publish" -e PORT="$PORT" \
      -v "$DATA_TARGET:/data" \
      -e LOCAL_PROTOCOL="$SCHEME" \
      -e HANJI_APP_ORIGIN="$origin" \
      -e HANJI_PASSKEY_RP_ID="$passkey_rp_id" \
      -e HANJI_PASSKEY_ORIGINS="$origin" \
      $proxy_args \
      $CERT_ARGS \
      --restart unless-stopped "$IMAGE" >/dev/null
  fi

  check_persist_capacity
  if ! wait_health; then
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    die "Hanji did not become ready. The data volume was kept."
  fi
  # Trigger/read the bootstrap state. Env-provisioned legacy installs must be
  # ready now; image-managed installs either offer setup or are already usable.
  bootstrap_body="$STATE_DIR/.instance-bootstrap-$$.json"
  umask 077
  : > "$bootstrap_body"
  trap 'rm -f "$bootstrap_body"' 0 1 2 15
  bootstrap_code=$(curl -sk --connect-timeout 2 --max-time 10 -o "$bootstrap_body" -w '%{http_code}' "$internal_origin/api/functions/instance-bootstrap" 2>/dev/null || echo 000)
  bootstrap_ready=1
  if [ "$ENV_ENABLED" -eq 1 ]; then
    grep -Eq '"masterConfigured"[[:space:]]*:[[:space:]]*true' "$bootstrap_body" || bootstrap_ready=0
    grep -Eq '"masterReady"[[:space:]]*:[[:space:]]*true' "$bootstrap_body" || bootstrap_ready=0
  else
    grep -Eq '"setupBlocked"[[:space:]]*:[[:space:]]*false' "$bootstrap_body" || bootstrap_ready=0
  fi
  setup_available=0
  grep -Eq '"setupAvailable"[[:space:]]*:[[:space:]]*true' "$bootstrap_body" && setup_available=1
  rm -f "$bootstrap_body"
  trap - 0 1 2 15
  if [ "$bootstrap_code" != 200 ] || [ "$bootstrap_ready" -ne 1 ]; then
    docker logs --tail 20 "$CONTAINER" 2>&1 || true
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    if [ "$DATA_KIND" = volume ]; then
      reset_hint="scripts/selfhost-docker.sh down && docker volume rm $DATA_TARGET"
    else
      reset_hint="scripts/selfhost-docker.sh down && rm -rf $DATA_TARGET"
    fi
    if [ "$bootstrap_code" = 200 ]; then
      warn "Instance bootstrap did not become usable."
      warn "Most often the existing /data ($DATA_TARGET) was first set up with"
      warn "different master credentials than the ones in $ENV_FILE."
      warn "Start fresh (this DELETES that data):  $reset_hint"
      warn "…then re-run. To keep the data, sign in with its original master account."
    fi
    die "Master-account bootstrap was not ready (HTTP $bootstrap_code). The data was kept."
  fi

  printf '\n'
  ok "Hanji is up."
  printf '  URL:      %s\n' "$origin"
  if [ "$ENV_ENABLED" -eq 1 ]; then
    email=$(grep '^HANJI_MASTER_EMAIL=' "$ENV_FILE" | cut -d= -f2-)
    password=$(grep '^HANJI_MASTER_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)
    printf '  Email:    %s\n' "$email"
    printf '  Password: %s\n' "$password"
  elif [ "$setup_available" -eq 1 ]; then
    setup_code=$(docker exec "$CONTAINER" node -e \
      'const fs=require("fs");const p=(process.env.PERSIST_DIR||"/data")+"/.hanji/runtime-secrets.json";process.stdout.write(JSON.parse(fs.readFileSync(p,"utf8")).HANJI_SETUP_TOKEN||"")')
    [ -n "$setup_code" ] || die "Could not read the first-run setup code from the container."
    printf '  Setup:    open the URL and create the first server administrator.\n'
    printf '  Code:     %s\n' "$setup_code"
  else
    printf '  Setup:    existing instance detected; sign in with its administrator account.\n'
  fi
  [ -n "$TLS_NOTE" ] && printf '  TLS:      %s\n' "$TLS_NOTE"
  printf '  Manage:   scripts/selfhost-docker.sh {logs|status|down}\n\n'
}

cmd_down()   { need_docker; docker rm -f "$CONTAINER" >/dev/null 2>&1 && ok "Stopped and removed '$CONTAINER' (persistent data and cert volumes kept)." || warn "No '$CONTAINER' container running."; }
cmd_logs()   { need_docker; docker logs -f "$CONTAINER"; }
cmd_status() { need_docker; docker ps -a --filter "name=$CONTAINER" --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'; }

# ── arg parsing ──────────────────────────────────────────────────────────────
ACTION=${1:-up}; [ $# -gt 0 ] && shift || true
while [ $# -gt 0 ]; do
  case "$1" in
    --port)     [ $# -ge 2 ] || die "--port requires a value."; PORT=$2; shift 2 ;;
    --email)    [ $# -ge 2 ] || die "--email requires a value."; MASTER_EMAIL=$2; shift 2 ;;
    --password) [ $# -ge 2 ] || die "--password requires a value."; MASTER_PASSWORD=$2; shift 2 ;;
    --data)     [ $# -ge 2 ] || die "--data requires a value."; DATA_TARGET=$2; shift 2 ;;
    --origin)   [ $# -ge 2 ] || die "--origin requires a value."; PUBLIC_ORIGIN=$2; shift 2 ;;
    --build)    FORCE_BUILD=1; shift ;;
    --http)     SCHEME=http; shift ;;
    -h|--help)  sed -n '2,30p' "$0"; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

if [ "$ACTION" = up ]; then
  validate_up_options
fi

case "$ACTION" in
  up)     cmd_up ;;
  down)   cmd_down ;;
  logs)   cmd_logs ;;
  status) cmd_status ;;
  -h|--help) sed -n '2,30p' "$0" ;;
  *) die "Unknown command: $ACTION (use up|down|logs|status)" ;;
esac
