#!/usr/bin/env node
// One-time local dev environment setup. Run from the repo root:
//   node scripts/setup-dev-env.mjs
//
// Interactively asks for the MASTER ACCOUNT (the first server administrator —
// see docs/master-account.md), generates fresh random dev secrets, and writes
// the git-ignored env files the dev servers need:
//   backend/.env.development  — dev secrets + master account
//   backend/.dev.vars         — same values for the wrangler runtime
//   web/.env.development.local — enables the local-only guest sign-in button
//
// Idempotent and non-destructive: existing files are never overwritten; if a
// backend env file predates the master-account keys, only the missing master
// block is appended. Non-interactive runs (CI, --yes) take the master
// credentials from HANJI_MASTER_EMAIL/HANJI_MASTER_PASSWORD or fall
// back to a printed random password.
import { randomBytes } from 'node:crypto';
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { fileURLToPath } from 'node:url';
import {
  legacyHanjiEnvAssignmentNames,
  legacyHanjiEnvironmentNames,
} from './migrate-hanji-local-namespace.mjs';

const defaultRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const secret = () => randomBytes(24).toString('hex');
const nonInteractive =
  process.argv.includes('--yes') || !process.stdin.isTTY || !process.stdout.isTTY;

function randomPassword() {
  // Satisfies the product policy: 10+ chars, upper/lower/digit/special.
  return `Hanji-${randomBytes(9).toString('base64url')}!7a`;
}

async function askMasterCredentials() {
  const envEmail = process.env.HANJI_MASTER_EMAIL?.trim();
  const envPassword = process.env.HANJI_MASTER_PASSWORD?.trim();
  if (nonInteractive) {
    const password = envPassword || randomPassword();
    if (!envPassword) {
      console.log(`generated master password: ${password}`);
      console.log('(store it — it is also written into backend/.env.development)');
    }
    return { email: envEmail || 'master@hanji.local', password };
  }
  console.log('Master account — the first server administrator (docs/master-account.md).');
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const email =
      (await rl.question(`Master email [${envEmail || 'master@hanji.local'}]: `)).trim() ||
      envEmail ||
      'master@hanji.local';
    const suggested = envPassword || randomPassword();
    const password =
      (await rl.question(`Master password (10+ chars, mixed) [${suggested}]: `)).trim() ||
      suggested;
    return { email, password };
  } finally {
    rl.close();
  }
}

function masterBlock(master) {
  return [
    '',
    '# Master account — provisioned automatically on first boot and promoted to',
    '# instance admin (docs/master-account.md). The password is only used when',
    '# the account is first created; change it later in Account Security.',
    `HANJI_MASTER_EMAIL=${master.email}`,
    `HANJI_MASTER_PASSWORD=${master.password}`,
    '',
  ].join('\n');
}

function backendEnv(master) {
  return [
    '# Local development secrets (git-ignored). Generated by scripts/setup-dev-env.mjs.',
    '# These are DEV-ONLY random values; production secrets live in .env.release.',
    `JWT_USER_SECRET=${secret()}`,
    `JWT_ADMIN_SECRET=${secret()}`,
    '',
    '# Service key for trusted admin/MCP access (local dev)',
    `SERVICE_KEY=${secret()}`,
    '',
    '# Per-workspace Durable Object split (required by the current data model)',
    'HANJI_WORKSPACE_DO_SPLIT=true',
    masterBlock(master),
  ].join('\n');
}

export async function setupDevEnvironment({ root = defaultRoot, environment = process.env } = {}) {
  const legacyProcessNames = legacyHanjiEnvironmentNames(environment);
  if (legacyProcessNames.length) {
    throw new Error(
      `Pre-Hanji environment variable names remain in the current process (${legacyProcessNames.join(', ')}). No files were changed. Rename or unset them before running setup.`,
    );
  }
  const backendEnvPaths = [
    join(root, 'backend', '.env.development'),
    join(root, 'backend', '.dev.vars'),
  ];
  const legacyFiles = backendEnvPaths.filter(
    (path) => existsSync(path) && legacyHanjiEnvAssignmentNames(readFileSync(path, 'utf8')).length,
  );
  if (legacyFiles.length) {
    throw new Error(
      `Pre-Hanji environment assignments remain in ${legacyFiles.length} backend env file(s). No files were changed. Run node scripts/migrate-hanji-local-namespace.mjs --dry-run, make the complete backup it requires, and apply that migration before setup.`,
    );
  }

  const master = await askMasterCredentials();
  const sharedBackendEnv = backendEnv(master);
  let changed = 0;

  for (const path of backendEnvPaths) {
    if (!existsSync(path)) {
      writeFileSync(path, sharedBackendEnv, { flag: 'wx' });
      console.log(`create ${path}`);
      changed += 1;
      continue;
    }
    let current = readFileSync(path, 'utf8');
    const withoutRetiredAutoLogin = current.replace(
      /^\s*HANJI_MASTER_DEV_AUTOLOGIN=.*(?:\r?\n|$)/gm,
      '',
    );
    if (withoutRetiredAutoLogin !== current) {
      writeFileSync(path, withoutRetiredAutoLogin);
      current = withoutRetiredAutoLogin;
      console.log(`update ${path} (remove retired master auto-login flag)`);
      changed += 1;
    }
    if (!current.includes('HANJI_MASTER_EMAIL=')) {
      appendFileSync(path, masterBlock(master));
      console.log(`append ${path} (master account block)`);
      changed += 1;
      continue;
    }
    console.log(`skip   ${path} (already set up)`);
  }

  const webEnvPath = join(root, 'web', '.env.development.local');
  if (existsSync(webEnvPath)) {
    console.log(`skip   ${webEnvPath} (already exists)`);
  } else {
    writeFileSync(
      webEnvPath,
      '# Enables the local-only "Continue as guest" dev button (git-ignored).\nVITE_ALLOW_ANONYMOUS_BOOTSTRAP=true\n',
      { flag: 'wx' },
    );
    console.log(`create ${webEnvPath}`);
    changed += 1;
  }

  console.log(
    changed
      ? `\nDone. Start the backend with: cd backend && npm run dev\nSign in as ${master.email} through the normal password form.`
      : '\nNothing to do — dev environment already set up.',
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    await setupDevEnvironment();
  } catch (error) {
    console.error(`FAIL Hanji dev environment setup: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
