#!/usr/bin/env node
// One-time local dev environment setup. Run from the repo root:
//   node scripts/setup-dev-env.mjs
//
// Generates fresh random dev secrets and writes the git-ignored env files the
// dev servers need. The first server administrator is deliberately not stored
// here: a fresh runtime asks for name/email/password in the browser.
//   backend/.env.development  — dev secrets + browser first-run setup
//   backend/.dev.vars         — same values for the wrangler runtime
//   web/.env.development.local — enables the local-only guest sign-in button
//
// Idempotent and migration-safe: existing secret values are preserved, retired
// master credential assignments are removed, and browser setup is enabled.
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  legacyHanjiEnvAssignmentNames,
  legacyHanjiEnvironmentNames,
} from './migrate-hanji-local-namespace.mjs';

const defaultRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const secret = () => randomBytes(24).toString('hex');

function browserSetupBlock() {
  return [
    '',
    '# A fresh local runtime creates its first server administrator in the browser.',
    'HANJI_BROWSER_SETUP=true',
    '',
  ].join('\n');
}

function backendEnv() {
  return [
    '# Local development secrets (git-ignored). Generated by scripts/setup-dev-env.mjs.',
    '# These are DEV-ONLY random values; production secrets live in .env.release.',
    `JWT_USER_SECRET=${secret()}`,
    `JWT_ADMIN_SECRET=${secret()}`,
    '',
    '# Service key for trusted admin/MCP access (local dev)',
    `SERVICE_KEY=${secret()}`,
    '',
    '# Per-workspace Durable Object split (required by the current data model)',
    'HANJI_WORKSPACE_DO_SPLIT=true',
    browserSetupBlock(),
  ].join('\n');
}

function migrateExistingBackendEnv(source) {
  let next = source.replace(
    /\n?# Master account[^\n]*\n(?:#[^\n]*\n){0,5}HANJI_MASTER_EMAIL=.*\nHANJI_MASTER_PASSWORD=.*(?:\n|$)/g,
    '\n',
  );
  next = next.replace(
    /^\s*(?:HANJI_MASTER_EMAIL|HANJI_MASTER_PASSWORD|HANJI_MASTER_DEV_AUTOLOGIN)=.*(?:\r?\n|$)/gm,
    '',
  );
  if (/^\s*HANJI_BROWSER_SETUP=/m.test(next)) {
    next = next.replace(/^\s*HANJI_BROWSER_SETUP=.*$/m, 'HANJI_BROWSER_SETUP=true');
  } else {
    next = `${next.replace(/\s*$/, '')}${browserSetupBlock()}`;
  }
  return next;
}

export async function setupDevEnvironment({ root = defaultRoot, environment = process.env } = {}) {
  const legacyProcessNames = legacyHanjiEnvironmentNames(environment);
  if (legacyProcessNames.length) {
    throw new Error(
      `Pre-Hanji environment variable names remain in the current process (${legacyProcessNames.join(', ')}). No files were changed. Rename or unset them before running setup.`,
    );
  }
  const backendEnvPaths = [
    join(root, 'backend', '.env.development'),
    join(root, 'backend', '.dev.vars'),
  ];
  const legacyFiles = backendEnvPaths.filter(
    (path) => existsSync(path) && legacyHanjiEnvAssignmentNames(readFileSync(path, 'utf8')).length,
  );
  if (legacyFiles.length) {
    throw new Error(
      `Pre-Hanji environment assignments remain in ${legacyFiles.length} backend env file(s). No files were changed. Run node scripts/migrate-hanji-local-namespace.mjs --dry-run, make the complete backup it requires, and apply that migration before setup.`,
    );
  }

  const sharedBackendEnv = backendEnv();
  let changed = 0;

  for (const path of backendEnvPaths) {
    if (!existsSync(path)) {
      writeFileSync(path, sharedBackendEnv, { flag: 'wx' });
      console.log(`create ${path}`);
      changed += 1;
      continue;
    }
    const current = readFileSync(path, 'utf8');
    const migrated = migrateExistingBackendEnv(current);
    if (migrated !== current) {
      writeFileSync(path, migrated);
      console.log(`update ${path} (browser first-run setup)`);
      changed += 1;
    } else {
      console.log(`skip   ${path} (already set up)`);
    }
  }

  const webEnvPath = join(root, 'web', '.env.development.local');
  if (existsSync(webEnvPath)) {
    console.log(`skip   ${webEnvPath} (already exists)`);
  } else {
    writeFileSync(
      webEnvPath,
      '# Enables the local-only "Continue as guest" dev button (git-ignored).\nVITE_ALLOW_ANONYMOUS_BOOTSTRAP=true\n',
      { flag: 'wx' },
    );
    console.log(`create ${webEnvPath}`);
    changed += 1;
  }

  console.log(
    changed
      ? '\nDone. Start the backend with: cd backend && npm run dev\nOpen http://localhost:8787 and create the first server administrator in the browser.'
      : '\nNothing to do — dev environment already set up.',
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    await setupDevEnvironment();
  } catch (error) {
    console.error(`FAIL Hanji dev environment setup: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
